security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            form_login:
                login_path: app_login
                check_path: app_login
            lazy: true
            provider: app_user_provider
            logout:
                path: app_logout
                target: app_login

    access_control:
     - { path: ^//la-caverne-secrete, roles: ROLE_ADMIN }