security:
    firewalls:
        admin:
            pattern: ^/la-caverne-secrete
            form_login:
                login_path: /login
                check_path: /la-caverne-secrete/login_check
                default_target_path: /test
                always_use_default_target_path: true
                enable_csrf: false
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: /la-caverne-secrete/logout
                target: /
                invalidate_session: true
            provider: app_user_provider
            security: true

    access_control:
        - { path: ^/la-caverne-secrete, roles: ROLE_ADMIN }

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    password_hashers:
        App\Entity\User:
            algorithm: auto
#        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
#            algorithm: auto

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
