controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_logout:
    path: /logout

admin:
    path: /la-caverne-secrete
    controller: App\Controller\Admin\DashboardController::index

login:
    path: /login
    controller: App\Controller\LoginController::login

login_check:
    path: /la-caverne-secrete/login_check